<?php

namespace Database\Seeders;

use App\Models\ReleaseNote;
use Illuminate\Database\Seeder;

class ReleaseNotesSeeder extends Seeder
{
    public function run(): void
    {
        $notes = [
            [
                'version' => '0.4.0',
                'type' => 'feature',
                'title' => 'Global search (⌘K)',
                'description' => 'Search across orders, companies, users, branches, collection points, service providers, waste streams, grades and container types from anywhere using ⌘K or Ctrl+K.',
                'released_at' => now(),
            ],
            [
                'version' => '0.4.0',
                'type' => 'feature',
                'title' => 'Notification bell',
                'description' => 'Admin users now receive in-app notifications for new features, bug fixes, backup results, and recurring order run summaries.',
                'released_at' => now(),
            ],
            [
                'version' => '0.4.0',
                'type' => 'feature',
                'title' => 'Wood material added',
                'description' => 'Wood has been added as a collectable material with full ordering and reporting support.',
                'released_at' => now(),
            ],
            [
                'version' => '0.4.0',
                'type' => 'improvement',
                'title' => 'Dashboard container breakdown',
                'description' => 'The dashboard now shows a per-container breakdown for better operational visibility.',
                'released_at' => now(),
            ],
            [
                'version' => '0.4.0',
                'type' => 'improvement',
                'title' => "Recurring orders run tomorrow's orders",
                'description' => "Scheduled recurring orders now generate for tomorrow's date as intended.",
                'released_at' => now(),
            ],
            [
                'version' => '0.4.0',
                'type' => 'improvement',
                'title' => 'Circularity (Reuse) renamed',
                'description' => 'The waste stream previously called "Avoidance" has been renamed to "Circularity (Reuse)" to better reflect its purpose.',
                'released_at' => now(),
            ],
            [
                'version' => '0.4.0',
                'type' => 'bugfix',
                'title' => 'Report totals fixed (Circularity Reuse)',
                'description' => 'Fixed report diversion totals and Total Waste Processed being incorrect after the Avoidance → Circularity (Reuse) rename. Wood Pallets now correctly count toward diverted waste.',
                'released_at' => now(),
            ],
            [
                'version' => '0.4.0',
                'type' => 'bugfix',
                'title' => 'Material usage shows branch name',
                'description' => 'Orders without a specific collection point (site) now display the branch name instead of "Unknown Site" on the material usage history.',
                'released_at' => now(),
            ],
            [
                'version' => '0.4.0',
                'type' => 'improvement',
                'title' => 'Notification detail modal',
                'description' => 'Clicking a notification now opens a modal with the full message instead of truncating the text. Use the × button to dismiss directly, or "Mark as read" from inside the modal.',
                'released_at' => now(),
            ],
            [
                'version' => '0.4.0',
                'type' => 'improvement',
                'title' => 'Material usage shows location type',
                'description' => 'The usage history on material pages now shows a small label (Site, Branch, or Company) beneath the location name, making it clear what level the order is linked to.',
                'released_at' => now(),
            ],
            [
                'version' => '0.4.0',
                'type' => 'improvement',
                'title' => 'Material usage history now links to orders',
                'description' => 'Each order in the material usage history is now clickable and navigates directly to the order detail page.',
                'released_at' => now(),
            ],
            [
                'version' => '0.4.0',
                'type' => 'improvement',
                'title' => 'Updated logo on collection summary PDF',
                'description' => 'The Summary of Orders for Collection PDF now displays the full WasteFlow logo instead of the icon-only version.',
                'released_at' => now(),
            ],
            [
                'version' => '0.4.0',
                'type' => 'feature',
                'title' => 'User impersonation for admins',
                'description' => 'Admins can now impersonate any non-admin user from the Edit User page to test their access and view the app as them. A yellow banner is shown while impersonating with a one-click stop button.',
                'released_at' => now(),
            ],
            [
                'version' => '0.4.0',
                'type' => 'bugfix',
                'title' => 'Resource Intelligence: Total Waste Processed corrected',
                'description' => 'Total Waste Processed now correctly shows Total Diverted + Total Disposal, matching the classification totals shown in the donut charts.',
                'released_at' => now(),
            ],
            [
                'version' => '0.4.0',
                'type' => 'improvement',
                'title' => 'Updated logo on collection order form PDF',
                'description' => 'The Waste Collection Order Form PDF now displays the full WasteFlow logo instead of the icon-only version.',
                'released_at' => now(),
            ],
            [
                'version' => '0.4.0',
                'type' => 'bugfix',
                'title' => 'Resource Intelligence: Wood and FOG Recovered now included',
                'description' => 'The grade table\'s "Organics Recovered" row has been replaced with "Total Recovery", which correctly includes all recovery materials (Organics, Wood, FOG Recovered, etc.). The Diversion Rate percentage is also now consistent with the donut chart.',
                'released_at' => now(),
            ],
            [
                'version' => '0.4.1',
                'type' => 'bugfix',
                'title' => 'Circularity (Reuse) now shows correctly in reports',
                'description' => 'Fixed a bug where Circularity (Reuse) weight was being counted as Material Recovery. The report table now shows separate rows for Organics Recovery, Material Recovery, Circularity (Reuse), and Total Recycling under a Waste Diverted section, with a TOTAL WASTE MANAGED grand total.',
                'released_at' => now(),
            ],
            [
                'version' => '0.4.1',
                'type' => 'improvement',
                'title' => 'Unified calculation engine',
                'description' => 'All environmental impact metrics (carbon, energy, water, trees, landfill space) now flow through a single shared calculation engine. Duplicate category-mapping loops have been removed, plastic grades are split correctly (PP/HD, PS, LDPE) with a fallback for unrecognised grades, and an organics double-count bug has been fixed. Dashboard and report carbon figures now match.',
                'released_at' => now(),
            ],
            [
                'version' => '0.4.1',
                'type' => 'feature',
                'title' => 'Document Library',
                'description' => 'Admins can now upload shared documents (title, description, and file) from the new Documents section in the sidebar. Everyone can view and download them, and a badge marks documents you have not opened yet.',
                'released_at' => now(),
            ],
            [
                'version' => '0.4.1',
                'type' => 'improvement',
                'title' => 'Roles now show descriptions',
                'description' => 'Each role in Roles & Permissions now has a plain-English description of what it grants. Cleaned up a few duplicate/unused permissions and made sure every permission is grouped into a section.',
                'released_at' => now(),
            ],
            [
                'version' => '0.4.1',
                'type' => 'improvement',
                'title' => 'Live search on Users page',
                'description' => 'Searching on the Users page now updates the list as you type instead of requiring a Filter click, and also matches against company name.',
                'released_at' => now(),
            ],
            [
                'version' => '0.4.1',
                'type' => 'bugfix',
                'title' => 'Roles table display fixed',
                'description' => 'Fixed role descriptions visually overlapping into the Permissions column on the Roles page, and trimmed the permission chips shown per role to 3 with a "+N more" indicator.',
                'released_at' => now(),
            ],
            [
                'version' => '0.4.1',
                'type' => 'improvement',
                'title' => 'Hide deleted recurring orders by default',
                'description' => 'The Recurring Orders list now hides deleted templates by default. Tick "Show deleted records" to bring them back into view, with a Restore action still available for each.',
                'released_at' => now(),
            ],
            [
                'version' => '0.4.1',
                'type' => 'feature',
                'title' => 'View documents inline',
                'description' => 'Added a "View" button on the Documents library to open files in a new tab for preview, alongside the existing Download option.',
                'released_at' => now(),
            ],
            [
                'version' => '0.4.1',
                'type' => 'feature',
                'title' => 'New Waste Stream Collection Report',
                'description' => 'Added a new standalone report, "Waste Stream Collection Report", grouping collections by waste stream and grade, with order number, collection date, slip number, and quantity per order and a weight subtotal per group. No pricing shown. Available from the Reports index with its own filters and PDF download.',
                'released_at' => now(),
            ],
            [
                'version' => '0.4.1',
                'type' => 'feature',
                'title' => 'Circular economy rate, barrels of oil, and homes powered metrics',
                'description' => 'Added three new metrics to the dashboard and monthly report Environmental Impact section: Circular Economy Rate (reuse + recycling + organics recovery as a share of total waste managed), Barrels of Oil Saved, and Homes Powered (1 Month) — both derived from energy saved through recycling.',
                'released_at' => now(),
            ],
            [
                'version' => '0.4.1',
                'type' => 'feature',
                'title' => 'Jan-Dec line graphs on the monthly report',
                'description' => 'The WasteFlow Resource Intelligence Report now includes two Jan-Dec line graphs: Monthly Material Recovery by Waste Grade (kg), and Waste Management Performance Trends (Total Waste Diverted, Waste to Landfill, Total Waste Managed).',
                'released_at' => now(),
            ],
            [
                'version' => '0.4.1',
                'type' => 'feature',
                'title' => 'New Management Report (all clients, one month)',
                'description' => 'Added a new cross-client Management Report showing total waste diverted % and container-type totals for every client in a single selected month, with CSV and PDF export. Available from the Reports index (requires the view-reports-all permission).',
                'released_at' => now(),
            ],
            [
                'version' => '1.8.0',
                'type' => 'feature',
                'title' => 'Custom date-range reporting',
                'description' => 'The WasteFlow Resource Intelligence Report (both the on-screen view and the PDF download) can now cover a custom period instead of just one calendar month — for example January to June. Use the new "From" and "To" month/year filters; leave "To" the same as "From" to get a normal single-month report like before.',
                'released_at' => now(),
            ],
            [
                'version' => '1.8.0',
                'type' => 'improvement',
                'title' => 'Resource Intelligence report: clearer metric names and a Recovery Rate figure',
                'description' => 'Renamed "Trees Saved" to "Trees Preserved" and "Landfill Space Saved" to "Landfill Airspace Saved" to match our standard reporting terminology, and added a dedicated Recovery Rate percentage next to Diversion Rate so every core sustainability indicator now has its own clearly labelled figure.',
                'released_at' => now(),
            ],
            [
                'version' => '1.8.0',
                'type' => 'feature',
                'title' => 'Release notes page',
                'description' => 'Click the version number next to "WasteFlow" in the sidebar to open a full history of every release, grouped by version with a description of what changed and why — features, fixes, and improvements all in one place, visible to every user.',
                'released_at' => now(),
            ],
            [
                'version' => '1.8.1',
                'type' => 'bugfix',
                'title' => 'Branded forgot password / reset password pages',
                'description' => 'The "Forgot your password?" and "Reset password" pages were still showing the plain default Laravel look instead of the WasteFlow branding used everywhere else in the portal (including the Login and Register pages). Both pages have been redesigned to match, with the same green branding, logo, and layout.',
                'released_at' => now(),
            ],
            [
                'version' => '1.8.2',
                'type' => 'bugfix',
                'title' => 'Admins are now notified of new user registrations',
                'description' => 'New user sign-ups are created inactive and need an admin to approve them, but until now nothing told anyone a new registration was waiting — you had to remember to check the Users page. Admins now get a bell notification and an email as soon as someone registers, with a link straight to the Users page to review and approve them.',
                'released_at' => now(),
            ],
            [
                'version' => '1.8.3',
                'type' => 'bugfix',
                'title' => 'Full audit and fix of unbranded pages',
                'description' => 'Checked every page in the portal for default, unbranded styling. Confirm Password and Verify Email were still using the plain default Laravel look — both now match the WasteFlow branding used everywhere else in the app (same layout as Login, Register, and the recently fixed Forgot/Reset Password pages).',
                'released_at' => now(),
            ],
            [
                'version' => '1.8.4',
                'type' => 'improvement',
                'title' => 'Password reset emails now go out via Communicator',
                'description' => 'Password reset (and email verification) emails now send through our internal Communicator service instead of always going out over SMTP, matching how other system emails already work. This also lays the groundwork for a reusable "julura/laravel-communicator" package we can install in other projects going forward.',
                'released_at' => now(),
            ],
            [
                'version' => '1.8.5',
                'type' => 'bugfix',
                'title' => 'Security hardening: document/slip access now correctly scoped per client',
                'description' => 'A full security review found that downloading, uploading, or deleting a collection document/slip did not check which client it belonged to. Fixed so this now follows the same per-client access rules already used everywhere else in the portal.',
                'released_at' => now(),
            ],
            [
                'version' => '1.8.6',
                'type' => 'feature',
                'title' => 'Configurable Resource Recovery Rating thresholds',
                'description' => 'New Settings > Resource Recovery Rating page lets admins set the diversion-rate cutoffs for each rating tier (Platinum, Gold, Silver, Bronze, Developing, Improvement Required).',
                'released_at' => now(),
            ],
            [
                'version' => '1.8.7',
                'type' => 'feature',
                'title' => 'Multi service-provider rebate support',
                'description' => 'Each load in an order can now specify its own service provider (defaulting to the order\'s provider) instead of every load sharing one provider. The Rebate Tracker report and PDF export now break out weight and rebate totals per provider.',
                'released_at' => now(),
            ],
            [
                'version' => '1.8.8',
                'type' => 'feature',
                'title' => 'Client Monthly Certificates',
                'description' => 'A "Download Certificate" button on the Resource Intelligence report page generates a branded Certificate of Waste Diversion for the selected client and month, showing their landfill diversion percentage and reporting period.',
                'released_at' => now(),
            ],
            [
                'version' => '1.8.9',
                'type' => 'feature',
                'title' => 'Carbon Avoidance Intensity (CAI) metric',
                'description' => 'New indicator on the Resource Intelligence report: kg CO2e avoided per kg of waste managed, a volume-independent measure of how carbon-efficient a client\'s diversion program is.',
                'released_at' => now(),
            ],
            [
                'version' => '1.9.0',
                'type' => 'bugfix',
                'title' => 'Corrected Resource Recovery Rating thresholds',
                'description' => 'Updated the Platinum/Gold/Silver/Bronze/Developing diversion-rate cutoffs to match the client\'s specification (defaults only; any admin-customized thresholds are preserved).',
                'released_at' => now(),
            ],
            [
                'version' => '1.9.0',
                'type' => 'bugfix',
                'title' => 'Carbon Avoidance Intensity now reported per ton',
                'description' => 'The CAI metric on the Resource Intelligence report was being calculated per kg of waste managed; it now correctly reports kg CO2e avoided per ton, matching the client\'s specification.',
                'released_at' => now(),
            ],
            [
                'version' => '1.9.0',
                'type' => 'feature',
                'title' => 'SHEQ Compliance document library',
                'description' => 'New "SHEQ Compliance" section (Safety, Health, Environment & Quality) for HSE File documents, alongside the existing Documents section. Staff can upload and manage files; all authenticated users can view and download.',
                'released_at' => now(),
            ],
            [
                'version' => '1.9.0',
                'type' => 'bugfix',
                'title' => 'Resource Intelligence "Generate PDF" button restored',
                'description' => 'The button that starts a Resource Intelligence PDF download had been missing from the report page since April. It has been restored, and the underlying download now renders correctly with all charts and tables (the same content shown when printing via Ctrl+P).',
                'released_at' => now(),
            ],
            [
                'version' => '1.9.0',
                'type' => 'improvement',
                'title' => 'Updated Methodology & Data Sources report copy',
                'description' => 'The Resource Intelligence report\'s Methodology & Data Sources section now includes the client\'s updated legal/trademark language: Resource Intelligence™ and Resource Recovery Rating™ trademark symbols, an expanded methodology and indicators list, and new Reporting Statement, Limitations, Disclaimer and copyright sections.',
                'released_at' => now(),
            ],
            [
                'version' => '1.10.0',
                'type' => 'feature',
                'title' => 'Client Hub adverts',
                'description' => 'Admins can now upload PNG/JPG/PDF adverts under Client Hub. Active adverts pop up automatically for clients on login. Closing the popup dismisses it (won\'t pop up again) but keeps the notification bell badge unread until the client actually opens it from the bell.',
                'released_at' => now(),
            ],
            [
                'version' => '1.10.1',
                'type' => 'bugfix',
                'title' => 'Corrected Barrels of Oil Saved and Homes Powered formulas to match EPA factors',
                'description' => 'Barrels of Oil Saved and Homes Powered (1 Month) were previously derived from energy saved (kWh); they are now derived from Total Lifecycle Carbon Avoided (kg CO2e), divided by the EPA Greenhouse Gas Equivalencies Calculator factors of 431.9 kg CO2e per barrel of oil and 399.83 kg CO2e per home\'s electricity use per month, matching the EPA\'s current published methodology.',
                'released_at' => now(),
            ],
            [
                'version' => '1.10.2',
                'type' => 'improvement',
                'title' => 'Baseline-year footnote added to Dashboard and Resource Intelligence Report',
                'description' => 'Added a "WasteFlow Resource Intelligence™ factors – baseline 2026" footnote to the Dashboard\'s Carbon equivalency indicators section and to the Resource Intelligence Report\'s Disclaimer section (web view and PDF), so clients know which year\'s conversion factors are in effect.',
                'released_at' => now(),
            ],
            [
                'version' => '1.10.3',
                'type' => 'bugfix',
                'title' => 'Fixed grey border and alignment issues on the Resource Intelligence Report PDF',
                'description' => 'The Resource Intelligence Report PDF (and print view) is generated from the same page as the Dashboard layout, whose grey page background and content padding were leaking through into print/PDF output as a grey frame around every page. The layout now goes edge-to-edge and white in print mode, and a dead "@page margin" CSS rule that was never actually applied by the PDF generator was removed.',
                'released_at' => now(),
            ],
            [
                'version' => '1.10.4',
                'type' => 'bugfix',
                'title' => 'Sidebar navigation now scrolls on short screens instead of hiding items',
                'description' => 'On shorter browser viewports (e.g. laptops with high display scaling), the bottom of the sidebar — including Documents, SHEQ Compliance, Client Hub and the collapse button — could be clipped off-screen with no way to reach it. The sidebar now scrolls as a whole so every item stays reachable regardless of screen height.',
                'released_at' => now(),
            ],
            [
                'version' => '1.10.5',
                'type' => 'feature',
                'title' => 'Manual ordering for SHEQ Compliance documents',
                'description' => 'Admins can now reorder SHEQ Compliance documents with move up/down controls instead of relying on filename or upload date. New uploads are appended to the end of the list.',
                'released_at' => now(),
            ],
            [
                'version' => '1.10.6',
                'type' => 'feature',
                'title' => 'Per-client visibility for SHEQ Compliance documents',
                'description' => 'Admins can now restrict a SHEQ Compliance document to specific companies via a "Visible to" selector when uploading or editing. Documents with no companies selected remain visible to all clients, matching the previous behaviour. Internal staff always see every document regardless of restriction.',
                'released_at' => now(),
            ],
            [
                'version' => '1.10.7',
                'type' => 'bugfix',
                'title' => 'Fixed "The file field must be a file" error when editing documents without replacing the file',
                'description' => 'Editing a Document, SHEQ Compliance document, or Client Hub advert without also choosing a replacement file always failed validation, because the upload form sends an empty placeholder value for the file field that Laravel was treating as an invalid file. Editing details (title, description, visibility, etc.) without touching the file now works correctly across all three.',
                'released_at' => now(),
            ],
            [
                'version' => '1.10.8',
                'type' => 'feature',
                'title' => 'Resource Recovery Rating now shown on the monthly certificate',
                'description' => 'The WasteFlow Resource Recovery Rating™ tier (Platinum through Improvement Required) is now resolved from the client\'s diversion percentage and shown on their monthly Certificate of Waste Diversion, colour-matched to the tier configured under Settings > Recovery Rating. Previously the tiers were fully configurable by admins but never surfaced anywhere in the app.',
                'released_at' => now(),
            ],
            [
                'version' => '1.10.9',
                'type' => 'feature',
                'title' => 'Automatic cleanup of old database backups on Wasabi',
                'description' => 'Database backups uploaded to Wasabi were never removed, so storage usage grew without bound. A new `backup:cleanup` command now deletes backup objects older than 7 days (configurable), and runs automatically every day shortly after the backup itself when scheduling is enabled.',
                'released_at' => now(),
            ],
            [
                'version' => '1.10.10',
                'type' => 'bugfix',
                'title' => 'Fixed Resource Intelligence report print pagination',
                'description' => 'The Waste Management Performance Trends chart title could land at the bottom of a page while its chart printed on the next, without a report header on the new page. It now moves to its own page with the report header intact. The Lifecycle Carbon Avoided paragraph in the methodology section could also split mid-sentence across a page break; it now stays intact on a single page.',
                'released_at' => now(),
            ],
            [
                'version' => '1.10.11',
                'type' => 'improvement',
                'title' => 'Resource Intelligence PDF filename now includes client name and period',
                'description' => 'Printing the Resource Intelligence report with Ctrl+P and saving as PDF used to suggest the same generic filename for every client. The suggested filename now includes the client name and reporting period, e.g. "Weskus Mall - WasteFlow Resource Intelligence Report - August 2026".',
                'released_at' => now(),
            ],
            [
                'version' => '1.10.12',
                'type' => 'improvement',
                'title' => 'SHEQ Compliance visibility is now role-based, not per-document',
                'description' => 'Previously each SHEQ Compliance document could be individually restricted to specific companies. Visibility is now controlled at the section level via a new "view-sheq-compliance" permission: anyone whose role has that permission sees the SHEQ Compliance menu item and every document in it. Create or edit a role under Settings > Roles to grant it, then assign that role to the users who need access.',
                'released_at' => now(),
            ],
            [
                'version' => '1.10.13',
                'type' => 'bugfix',
                'title' => 'Fixed certificate date wrapping onto the "Date" label',
                'description' => 'On the Certificate of Waste Diversion PDF, dates for months with longer names (e.g. "31 AUGUST 2026", "30 SEPTEMBER 2026") could wrap onto a second line and overlap the "Date" label printed below it. The date field now shrinks its font size for longer dates so it always stays on one line.',
                'released_at' => now(),
            ],
            [
                'version' => '1.10.14',
                'type' => 'bugfix',
                'title' => 'Fixed long company names wrapping on the certificate',
                'description' => 'Customers sent screenshots of certificates where longer company names ("DEVONBOSCH ESTATE", "VAN RIEBEECKSTRAND PRIMARY SCHOOL") wrapped onto a second line and overlapped the summary text below, and even short names sat flush against the "WASTEFLOW CONGRATULATES" label with no gap. The company-name field is now wider (there was far more clear space on the certificate background than previously used) and starts further down, so names render larger and no longer collide with the text above or below them.',
                'released_at' => now(),
            ],
            [
                'version' => '1.10.15',
                'type' => 'bugfix',
                'title' => 'Hid the Provider column from clients on the Waste Collection & Recycling report',
                'description' => 'The "Rebate by Service Provider" breakdown box was already hidden from client logins, but the per-row Provider column in the main table was not, so clients could see which service provider handled each load. The Provider column is now hidden for clients on both the on-screen report and the downloaded PDF, matching the breakdown box.',
                'released_at' => now(),
            ],
            [
                'version' => '1.10.16',
                'type' => 'feature',
                'title' => 'Client Hub menu item for clients',
                'description' => 'Clients previously only saw Client Hub adverts via a one-time popup on login and the notification bell - once dismissed, there was no way to find one again. A "Client Hub" link now appears in the sidebar for client logins (alongside Documents and SHEQ Compliance), showing all of their active adverts with read/unread status so they can revisit any of them at any time.',
                'released_at' => now(),
            ],
            [
                'version' => '1.10.17',
                'type' => 'bugfix',
                'title' => 'Sharpened the "WasteFlow Congratulates" text on the certificate',
                'description' => 'The client sent us their original certificate design as a reference, showing crisp text where ours looked visibly softer. The "WASTEFLOW CONGRATULATES" label was flattened into the certificate\'s background image, so it inherited that image\'s JPEG compression while every other field on the certificate rendered as sharp live text. It now renders as live text too, matching the reference design.',
                'released_at' => now(),
            ],
        ];

        foreach ($notes as $note) {
            ReleaseNote::firstOrCreate(
                ['version' => $note['version'], 'title' => $note['title']],
                $note
            );
        }
    }
}
