<?php

namespace App\Http\Controllers;

use App\Models\ActivityLog;
use App\Models\Company;
use App\Models\ContainerOption;
use App\Models\Order;
use App\Models\ServiceProvider;
use App\Models\Site;
use App\Support\DisplayDate;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Inertia\Inertia;

class OrderSeederController extends Controller
{
    /**
     * Display the order seeder page.
     */
    public function index()
    {
        $companies = Company::where('is_active', true)->orderBy('name')->get();

        return Inertia::render('Orders/Seeder', [
            'companies' => $companies,
        ]);
    }

    /**
     * Generate orders for testing.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'company_id' => 'required|exists:companies,id',
            'recycling_order_count' => 'required|integer|min:0|max:1000',
            'waste_order_count' => 'required|integer|min:0|max:1000',
            'month' => 'required|date_format:Y-m',
            'status' => 'required|in:pending,scheduled,weight_required,documents_required,finalized',
        ]);

        $company = Company::findOrFail($validated['company_id']);

        // Get all sites for the company (through branches)
        $sites = Site::whereHas('branch', function ($query) use ($company) {
            $query->where('company_id', $company->id);
        })->where('is_active', true)->get();

        if ($sites->isEmpty()) {
            return back()->withErrors([
                'company_id' => 'The selected company has no active sites. Please create sites first.',
            ]);
        }

        // Get active service providers
        $serviceProviders = ServiceProvider::active()->get();

        if ($serviceProviders->isEmpty()) {
            return back()->withErrors([
                'service_providers' => 'No active service providers found. Please create service providers first.',
            ]);
        }

        $month = Carbon::parse($validated['month'].'-01');
        $startDate = $month->copy()->startOfMonth();
        $endDate = $month->copy()->endOfMonth();

        // Only generate weekdays (Monday-Friday)
        $workdays = [];
        $currentDate = $startDate->copy();
        while ($currentDate->lte($endDate)) {
            if ($currentDate->isWeekday()) {
                $workdays[] = $currentDate->copy();
            }
            $currentDate->addDay();
        }

        if (empty($workdays)) {
            return back()->withErrors([
                'month' => 'The selected month has no weekdays.',
            ]);
        }

        $createdOrders = [];
        $errors = [];

        try {
            DB::beginTransaction();

            // Generate recycling orders
            for ($i = 0; $i < $validated['recycling_order_count']; $i++) {
                try {
                    $site = $sites->random();
                    $serviceProvider = $serviceProviders->random();
                    $requestedDate = $workdays[array_rand($workdays)];

                    $recyclingOption = ContainerOption::query()
                        ->where('order_type', 'recycling')
                        ->where('is_active', true)
                        ->inRandomOrder()
                        ->first();
                    if (! $recyclingOption) {
                        $errors[] = 'No active recycling container options in settings. Add some under Settings → Container Options.';

                        continue;
                    }
                    $qty = rand(1, 10);
                    $quantityLines = [
                        [
                            'container_option_id' => $recyclingOption->id,
                            'container_option_name' => $recyclingOption->name,
                            'quantity' => $qty,
                        ],
                    ];

                    $order = Order::create([
                        'company_id' => $company->id,
                        'branch_id' => $site->branch_id,
                        'site_id' => $site->id,
                        'service_provider_id' => $serviceProvider->id,
                        'created_by' => auth()->id(),
                        'order_type' => 'recycling',
                        'status' => $validated['status'],
                        'quantity_lines' => $quantityLines,
                        'estimated_quantity' => $qty,
                        'requested_collection_date' => $requestedDate->format('Y-m-d'),
                        'notes' => 'Generated by Order Seeder for testing',
                    ]);

                    $createdOrders[] = $order->tracking_number;
                } catch (\Exception $e) {
                    $errors[] = 'Failed to create recycling order '.($i + 1).': '.$e->getMessage();
                }
            }

            // Generate waste orders
            for ($i = 0; $i < $validated['waste_order_count']; $i++) {
                try {
                    $site = $sites->random();
                    $serviceProvider = $serviceProviders->random();
                    $requestedDate = $workdays[array_rand($workdays)];

                    $wasteOption = ContainerOption::query()
                        ->where('order_type', 'waste')
                        ->where('is_active', true)
                        ->inRandomOrder()
                        ->first();
                    if (! $wasteOption) {
                        $errors[] = 'No active waste container options in settings. Add some under Settings → Container Options.';

                        continue;
                    }
                    $qty = rand(1, 10);
                    $quantityLines = [
                        [
                            'container_option_id' => $wasteOption->id,
                            'container_option_name' => $wasteOption->name,
                            'quantity' => $qty,
                        ],
                    ];

                    $order = Order::create([
                        'company_id' => $company->id,
                        'branch_id' => $site->branch_id,
                        'site_id' => $site->id,
                        'service_provider_id' => $serviceProvider->id,
                        'created_by' => auth()->id(),
                        'order_type' => 'waste',
                        'status' => $validated['status'],
                        'quantity_lines' => $quantityLines,
                        'estimated_quantity' => $qty,
                        'requested_collection_date' => $requestedDate->format('Y-m-d'),
                        'notes' => 'Generated by Order Seeder for testing',
                    ]);

                    $createdOrders[] = $order->tracking_number;
                } catch (\Exception $e) {
                    $errors[] = 'Failed to create waste order '.($i + 1).': '.$e->getMessage();
                }
            }

            DB::commit();

            ActivityLog::log('orders_seeded', sprintf(
                'Order seeder created %d orders for %s in %s',
                count($createdOrders),
                $company->name,
                $month->format(DisplayDate::CALENDAR)
            ), null, [
                'company_id' => $company->id,
                'company_name' => $company->name,
                'order_count' => count($createdOrders),
                'recycling_count' => $validated['recycling_order_count'],
                'waste_count' => $validated['waste_order_count'],
                'month' => $validated['month'],
                'tracking_numbers' => $createdOrders,
            ]);

            $message = sprintf(
                'Successfully created %d orders (%d recycling, %d waste) for %s in %s.',
                count($createdOrders),
                $validated['recycling_order_count'],
                $validated['waste_order_count'],
                $company->name,
                $month->format(DisplayDate::CALENDAR)
            );

            if (! empty($errors)) {
                $message .= ' However, some errors occurred: '.implode('; ', $errors);
            }

            return back()->with('success', $message);
        } catch (\Exception $e) {
            DB::rollBack();

            return back()->withErrors([
                'general' => 'An error occurred while generating orders: '.$e->getMessage(),
            ]);
        }
    }
}
